### ISSUE TITLE
Add new functionality to copy from git repo and can specify branch & folder inside.

### ISSUE THREAD

**Issue by pjamenaja** [its-software-services-devops/iasc#17]
```YAML
copy:
  - from: https://github.com/its-software-services-devops/iasc.git
    branch: master
    folder: xxxx
    toDir: ""
```

Program will recursively copy files inside xxxx folder to toDir in the workspace directory.
